// Login Container Actions
export const SIMPLE_ACTION = 'SIMPLE_ACTION';

export const ACTION_TYPE_2 = 'ACTION_TYPE_2';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_PLANETS_SUCCESSFUL = 'GET_PLANETS_SUCCESSFUL';
export const GET_PLANETS_FAILED = 'GET_PLANETS_FAILED';
